### ISSUE TITLE
Fix for bricked radios

### ISSUE THREAD

**Issue by lormaccone** [piotr022/UV_K5_playground#15]
Your bricked radios may not be bricked after all. Switch it on with PTT pressed. If the flashlight turns on, then you can flash the firmware. If it doesn't work, try it multiple times. It worked for me at the 5th or 6th try. My radio was totally bricked (didn't even turn on), now it works perfectly again.

Thanks for your hack!
Lorenzo

**Comment by piotr022** [comment]
Hi Lorenzo, thank you for your message. What you are talking about is the functionality of the bootloader that resides in the first 0x1000 bytes of memory. I bricked my radios while attempting to run par_runner for the first time. Instead of using the stock bootloader (via UART - using this USB cable for programming), I used SWD and a debug adapter to flash it. In the process, I accidentally overwrote the bootloader area with the original firmware, which disabled the SWD pins during runtime. Consequently, I no longer have the option to enter bootloader mode (PTT+power on) because, as I mentioned earlier, I accidentally overwrote it. Even i was trying to connect to dap under reset, but no idea why it is not responding
